### ISSUE TITLE
Are you planning to bump a new NPM version?

### ISSUE THREAD

**Issue by ricardopolo** [danielzzz/node-ping#102]

**Comment by ajimix** [comment]
@danielzzz would be great if you can push the latest version to npm as it's quite outdated there

**Comment by Coding-Kiwi** [comment]
yes please ^^
I've been searching for 1 hour why the package does ipv6 pings eventhough I passed the v6: false option, the reason was that the npm package simply doesn't have this option yet

**Comment by mondwan** [comment]
0.2.3. Please check them out
