### ISSUE TITLE
WSL bash always returns host down

### ISSUE THREAD

**Issue by roughnecks** [danielzzz/node-ping#111]
Hello, here's my script:

```
var ping = require('ping');
const fs = require('fs');

var hosts = ['192.168.1.253'];
hosts.forEach(function(host){
    ping.sys.probe(host, function(isAlive){
        if (isAlive) {
            return;
        } else {
            d = new Date().toLocaleString();
            fs.appendFile("/mnt/c/Users/roughnecks/Desktop/ping.txt", "Access Point is Down! - " + d + "\n" , function(err) {
                if(err) {
                    return;
                }
                //console.log("The file was saved!");
            });
        }
    });
});
```

This used to work but for some reason on my new WSL Debian install it always reports "host down",
Can you help?

roughnecks@CUSPIDE:~$ node --version
v12.16.1

roughnecks@CUSPIDE:~$ cat /etc/debian_version
10.3

Thanks

**Comment by mondwan** [comment]
I suggest you to rewrite this program with promise based. Then, try to take
a look the error from the promised, and see what's happening

Simone <notifications@github.com> 於 2020年2月27日週四 上午12:06寫道：

**Comment by roughnecks** [comment]
New script, just copy-pasted from README:

```
var ping = require('ping');

var hosts = ['192.168.1.253'];

hosts.forEach(function (host) {
    ping.promise.probe(host)
        .then(function (res) {
            console.log(res);
        });
});
```

roughnecks@CUSPIDE:~/scripts$ node pingpromise.js                                                                       {
  host: 'unknown',
  alive: false,
  output: '',
  time: 'unknown',
  min: 'unknown',
  max: 'unknown',
  avg: 'unknown',
  stddev: 'unknown'
}

**Comment by mondwan** [comment]
Since you have installed a new system, did you install ping in your system?

Simone <notifications@github.com> 於 2020年2月27日週四 上午12:24寫道：

**Comment by roughnecks** [comment]
I have installed with:

`npm install ping`

Now I also tried with:

`npm install node-ping`

But it's still not working

**Comment by mondwan** [comment]
No. I mean the ping in your system. Can you run ping in your debian
terminal?

Simone <notifications@github.com> 於 2020年2月27日週四 上午12:31寫道：

**Comment by roughnecks** [comment]
Yes, it's installed but it doesn't actually work.

"ping: socket: Operation not permitted"

I wonder how did I manage to have it working in my old setup, which was pretty much the same.

**Comment by roughnecks** [comment]
Hey, I fixed it by running this:

`sudo chmod u+s `which ping``

Which was referenced here: https://github.com/microsoft/WSL/issues/18#issuecomment-463743967
