### ISSUE TITLE
Pinged 73 IPs got response as 58, it does not provide the response for all IPs

### ISSUE THREAD

**Issue by debjava** [danielzzz/node-ping#120]
Hi, I tried to ping 73 IP addresses, but unfortunately I got response from 58 addresses. All IP addresses may not be reachable but We get response from all IP addresses whatever we have pinged. For a small set of IP addresses like 5 IPs, 10 IPs, it works but it does not work for 50, 70, 100, 500 IP addresses where we pass all IP addresses in a for loop.

You can see my complete small standalone project in github. I provide below the github link. Please help us in this regard.

https://github.com/debjava/ping-ip-address-nodeJs

To run the project, use the following command, you can see simple log messages in the console.

**yarn install && yarn build && yarn start**

**Comment by mondwan** [comment]
For a standard promise object, there are `.then`, and `.catch` for handling a success or a failure result respectively.

As my quick glance on your project, you have not implemented `.catch`. Since some IPs are missing in the map, they may fall into catch case with unknown reasons. Try to implement `.catch`, and take a look why is it error, and let us know here

**Comment by debjava** [comment]
If you look into the following code structure, I am able to print all the IP addresses in the array.
So, I am assuming that I am passing all IPs.

`console.log("Total IPs to Ping: ", allIPs.length); // It prints 73 IPs
`
```
public async pingAllIPs_Type2(): Promise<void> {
        const start = now();
        const fileUtil = new FileUtil();
        const allIPs: string[] = await fileUtil.readFileLineByLineNonBlocking(Test.FILENAMEPATH);
        const pingUtil = new IPPingUtil();
        const map: Map<string, boolean> = await pingUtil.pingManyIPAddress_Type2(allIPs);
//        if(allIPs.length !== map.size) throw Error("Unexpected error ...");
        
        for (const [key, value] of map.entries()) {
            console.log(key + ' : ' + value)
        }
        
        console.log("Total IPs to Ping: ", allIPs.length);
        console.log("Total IPs Pinged: ", map.size);
        
        const end = now();
        const timeInSeconds = (end - start)/ 1000;
        console.log("Total time taken : ", timeInSeconds, "seconds");
    }
```

**Comment by debjava** [comment]
Do a small litmus test, try to ping the following 3 IP addresses where one IP address has been repeated, it mean one IP address is duplicate.

100.64.47.81, 255.128.0.1, 100.64.47.81

Can I expect **3** responses or can I expect **2** responses ?

As per the API, I am getting two responses. But I should get 3 responses in reality even if the IP is duplicate.

**Comment by mondwan** [comment]
In your code, you are using map to store result with ip as index. Therefore, duplicated ip will override the responses at all.

**Comment by mondwan** [comment]
> If you look into the following code structure, I am able to print all the IP addresses in the array.
> So, I am assuming that I am passing all IPs.
> 
> `console.log("Total IPs to Ping: ", allIPs.length); // It prints 73 IPs `
> 
> ```
> public async pingAllIPs_Type2(): Promise<void> {
>         const start = now();
>         const fileUtil = new FileUtil();
>         const allIPs: string[] = await fileUtil.readFileLineByLineNonBlocking(Test.FILENAMEPATH);
>         const pingUtil = new IPPingUtil();
>         const map: Map<string, boolean> = await pingUtil.pingManyIPAddress_Type2(allIPs);
> //        if(allIPs.length !== map.size) throw Error("Unexpected error ...");
>         
>         for (const [key, value] of map.entries()) {
>             console.log(key + ' : ' + value)
>         }
>         
>         console.log("Total IPs to Ping: ", allIPs.length);
>         console.log("Total IPs Pinged: ", map.size);
>         
>         const end = now();
>         const timeInSeconds = (end - start)/ 1000;
>         console.log("Total time taken : ", timeInSeconds, "seconds");
>     }
> ```

Yes. You have passed all the IPs into your library. But, my point is your library need to deal with the `.catch` part.

For example, you pass, and ping 73 IPs. But, you have `.then()` without `.catch()`. Some of the ping may fail silently as a result.

**Comment by debjava** [comment]
Excellent Mond, thank you very much for quick response. Let me close it.

**Comment by debjava** [comment]
Issue resolved.
