### ISSUE TITLE
not working in production

### ISSUE THREAD

**Issue by charly-rocks-app** [danielzzz/node-ping#126]
Hey.

When I run this code in the test environment (localhost on Windows) it works fine. When I run the productive (example.com on CentOS 7) I get error messages. I'm using nodeJS 10.16.0:

HOST: unknown
ALIVE: false
OUTPUT:

I hope you can help ;-)

`
const hosts = await pingServiceModel.find().sort('title')
`

JSON Output:
`
[{
            "_id":"5f4cdc2a6f2f20af04cdb87a",
            "title":"Google",
            "url":"google.com"
        },{
            "_id":"5f4cd9d0421ccfe2a09c5fcd",
            "title":"Facebook",
            "url":"facebook.com"
    }]
`

`hosts.forEach(function (host) {
        ping.promise.probe(host.url)
            .then(function (res) {
                if (res.alive) online.push(host)
                else offline.push(host)
                outputs.push(res)
            });
    });`

**Comment by mondwan** [comment]
what is the error message?

**Comment by charly-rocks-app** [comment]
From the promise-resource:

HOST: unknown
ALIVE: false
OUTPUT:

**Comment by mondwan** [comment]
I am not following. What kind of error message you expect? It sounds like the domain you ping is not alive at all.

However, since you are pinging domain like google.com, which should not have down time, I suspect the functionality of DNS in your production work station. Did you try to ping those domain manually in command line by issuing `ping` command?

**Comment by charly-rocks-app** [comment]
Dear mondwan,

here three screenshots:

The `ping` on the server:
![ss-server-ping](https://user-images.githubusercontent.com/61018110/92362542-6d9c5280-f0f0-11ea-8c81-c81467b04ecc.jpg)

The ping on development-server (localhost)
![ss-ping-development](https://user-images.githubusercontent.com/61018110/92362590-7d1b9b80-f0f0-11ea-92a3-70431d4d5594.jpg)

The ping on the production-server (online)
![ss-ping-production](https://user-images.githubusercontent.com/61018110/92362627-8b69b780-f0f0-11ea-9dc4-fc14d2df5af7.jpg)

**Comment by mondwan** [comment]
The ping command cannot be execute in your production at all since the output is an empty string. The question is why.

* Which library version u r using?
* What kind of user's permission u r using in your production environment?
    * since in ur screen capture 1, u r running in root permission, which generally should not be the permission in your production site

**Comment by charly-rocks-app** [comment]
Hey mondwan,

the root account I'm only using only for me.

Node: 10.16.0
"ping": "^0.2.3"

**Comment by mondwan** [comment]
@charly-rocks-app Hey, after patches from #122 , #128 , we may get new clues on your issue. Can you try again on master branch?

**Comment by mondwan** [comment]
Reopen it if you think the problem still here
