### ISSUE TITLE
Multiple interface on debian

### ISSUE THREAD

**Issue by victorbillaud** [danielzzz/node-ping#137]
Hello, 
I have a little problem, my server have 2 differents ip, one for internet connexion and one for local network with robots.
On my server i have two network interfaces. It's possible to specifie the good interface in ping request ?

**Comment by mondwan** [comment]
Depends on your platform, you can specify custom option.

For example, Linux one, you can use -I eth1

Ping 8.8.8.8 -I eth1



在 2021年4月23日週五 20:04，victorbillaud ***@***.***> 寫道：

**Comment by victorbillaud** [comment]
I spoke about npm ping with node js

**Comment by mondwan** [comment]
In debian system, I believe `{..., extra: ['-I', 'THAT_INTERFACE']}` should do the trick

**Comment by victorbillaud** [comment]
Oh thanks for this answer, i will try this monday.
Have a nice evening
