### ISSUE TITLE
Reporting round trip time aka lag interval?

### ISSUE THREAD

**Issue by lolmaus** [danielzzz/node-ping#14]
Hi!

Tried `ping` like this:

```
timeout = 15
host = '8.8.8.8'

#-----------------------------

ping = require 'ping'

ping.sys.promise_probe host,
  timeout: timeout
.then (res) ->
  console.log(res)
```

The `res` only reports the hostname and a boolean status:

```
{
  host: '8.8.8.8',
  alive: true
}
```

I want to know the round trip time in milliseconds. How do i do that?

**Comment by mondwan** [comment]
According to implementation in #39, round-trip-time has been implemented.

**Comment by mondwan** [comment]
close #14

**Comment by lolmaus** [comment]
Thank you so much!

Any ETA for it to hit npm?

**Comment by mondwan** [comment]
Hello @danielzzz, as we have do much since last release (I guess), I suggest to increase the major version number when you update the package in npm.

**Comment by mysticflute** [comment]
Is there any reason this hasn't been updated in npm yet?

**Comment by mondwan** [comment]
v0.2.0 has been published on npm. closed

**Comment by lolmaus** [comment]
Thank you! :bow: :beers:
