### ISSUE TITLE
Unable to ping IPv6 address - There is no timeout option on ping6

### ISSUE THREAD

**Issue by jpheneger** [danielzzz/node-ping#145]
I am attempting to use this library in an application which runs on MacOS and I get the error "There is no timeout option on ping6" when v6 == true, even when timeout is not provided in the config or explicitly set to null.

The problem code appears to be:
if (_config.timeout) {
    // XXX: There is no timeout option on mac's ping6
    if (config.v6) {
        throw new Error('There is no timeout option on ping6');
    }

    ret = ret.concat([
        '-W',
        util.format('%d', _config.timeout * 1000),
    ]);
}

This logic should probably be inverted where the outer check is for v6 and skips timeout if v6 is true.

**Comment by jpheneger** [comment]
I tried to create a pull request but got a permission denied error.  Here is the suggested fix:

if (!_config.v6 && _config.timeout) {
        // Only set timeout when *not* using IPv6 as there is no timout option on mac's ping6
        ret = ret.concat([
            '-W',
            util.format('%d', _config.timeout * 1000),
        ]);
    }

**Comment by mondwan** [comment]
You need to set `timeout` as `False` instead of `null`. Then, you will not hit that condition. 

Checkout the note in the README. By setting certain options to false, you can "disable" them from being run at all
