### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by LmonZero** [danielzzz/node-ping#150]
I looked at the bottom of the library and found that "spawn" was used, but when processing the I/O output text of ping, the I/O output of some devices with poor network may not meet this rule, causing the Node program to crash

**Comment by danielzzz** [comment]
hi, thanks, are you getting some error trace?

this, or a PR might be very helpful.

thanks! dan

**Comment by mondwan** [comment]
* Please point us the file & line number
* The only one `spawn` I found is under `ping-promise.js`. That call is wrapped in `try-catch` already. Therefore, for your case, it should return an error promise that you can handle in your codes.

reopen it if you have any more concerns
