### ISSUE TITLE
Bug: Response data comes back with unknowns.

### ISSUE THREAD

**Issue by DIBSTERYT** [danielzzz/node-ping#156]
System: Debian GNU/Linux 10 (buster) x86_64 
Version: 0.4.2

Response: 
```
{
  inputHost: 'dibster.live',
  host: 'unknown',
  alive: false,
  output: '',
  time: 'unknown',
  times: [],
  min: 'unknown',
  max: 'unknown',
  avg: 'unknown',
  stddev: 'unknown',
  packetLoss: 'unknown'
}
```

On my Windows 10 laptop I am able to get perfect responses with the same package version and same request code. Double checked with the website, it is up, double checked on my laptop, works fine. Assuming an issue with Linux specifically.

**Comment by mondwan** [comment]
It looks like the ping command cannot be run at all as output is an empty
string.

Do you have system ping installed? Is it installed in system path?

I will suggest you try the ping command on your own terminal first

**Comment by DIBSTERYT** [comment]
After some testing I was able to figure out that is wasn't installed for some reason, I appreciate the help!
