### ISSUE TITLE
no warning when ping is not installed

### ISSUE THREAD

**Issue by sunny-Ne5** [danielzzz/node-ping#160]
I was using node-ping inside a docker container which doesn't had iputils-ping installed.
`    ping.sys.probe(req.params.ip, (isUp) => {
        res.end(JSON.stringify({status: isUp ? "true" : "false"}));
      });
`
`isUp` was always coming as null with no warning whatsoever that ping is not installed in the system.
However, installing iputils-ping inside container fixed the issue. 

Should we throw warning for this use case?
I'll be happy to add the fix if given some guidance.

**Comment by mondwan** [comment]
Hi,

Have you tried the promise base response? I suppose it should fit your need

**Comment by sunny-Ne5** [comment]
Hi mondwan, as I mentioned installing ping fixed the issue for me but it took me sometime to figure that out. Ideally library should have throwed a warning that ping is not installed.

**Comment by mondwan** [comment]
Thanks for the report.

But, what I mean is that the error message you need will be presented
within the promise based response.

The callback style interface is kind of a legacy. There is a ticket for
aligning the response between the callback, and the promise interface. Just
so happened that we haven't decided when to do such enhancement yet.

**Comment by sunny-Ne5** [comment]
Got it, thanks 😃. Will add the promise based approach. Closing this ticket.
