### ISSUE TITLE
Is it possible to set timeout < 1 sec

### ISSUE THREAD

**Issue by SubliminalGuy** [danielzzz/node-ping#161]
Hi! Thank you for this useful and well working package. Just one quick question: Is it possible to set the timeout in milliseconds or as a float value (e.g. 0.4)? If not what would you suggest to reduce the timeout lower than one second?

**Comment by mondwan** [comment]
Hello,

As this library is just a wrapper for the underlying system ping
executable, the question you ask depends whether or not such option had
been provided by the underlying executable.

For example, in window's ping, the unit of option W is milli seconds.
Therefore, the timeout option will be in msec when you are on window
platform. However, that's not the case if you are on Linux platforms. As
the unit of option W in Linux is Seconds

If you really want to run ping within a second in Linux platforms, you may
need to Google a bit, and see how to make it work on Linux platforms first.

If there is an executable you found that work with msec, you can config
this library to point to your ping executable, and run it accordingly
