### ISSUE TITLE
Error: spawn EPERM on Pterodactyl Server

### ISSUE THREAD

**Issue by lighscent** [danielzzz/node-ping#163]
![image](https://github.com/danielzzz/node-ping/assets/93555197/17984e80-450b-4119-8e20-16f29b9739ef)

**Comment by Azukiov** [comment]
this is my code

```js
const ping = require('ping')
const proxyPing = await ping.promise.probe("play.maskfr.org");
console.log(proxyPing.avg)
```

**Comment by mondwan** [comment]
Usually, for EPERM, it means you don't have sufficient permissions to run
the ping command in your host.

Can you try whether you can run system ping locally in a terminal?

**Comment by Azukiov** [comment]
I just ran the `ping IP` command via SSH and it works perfectly.

**Comment by mondwan** [comment]
How about the one running ping via nodejs?

As my guess, EPERM related to the permissions. As long as you can figured
out which part got permission denied, you find the solution

**Comment by mondwan** [comment]
One more thing you can look for, which is The path of the ping executable.

In this library, we expect the ping executable located in the default
system path like /bin etc. If your host setup is a little bit different,
you can configure the path yourself. Please take a look the document in the
readme if you need to configure the path
