### ISSUE TITLE
Datadog Synthetic Monitoring:  ICMP Test on Windows Machine Not Working

### ISSUE THREAD

**Issue by bhsi-gbarbosa** [danielzzz/node-ping#165]
I've setup a datadog synthetics worker on a Windows 10 machine and getting the following error,
"There is no deadline option on Windows"
This error appears to cause the ICMP Test to fail all together.

I'm running the HTTP Test without any issues from the same synthetics worker.

Attaching the debug log for your review. Thanks in advance.
[private-location-service.out.log](https://github.com/danielzzz/node-ping/files/14316661/private-location-service.out.log)

**Comment by bhsi-gbarbosa** [comment]
I'm running the default config. I didn't make any changes to any of the files.
Do I need to make any config changes to disable the deadline option?
Thanks in advance.

**Comment by mondwan** [comment]
Try setting the deadline option to be `false` or `null`.
