### ISSUE TITLE
Destination host unreachable - not working

### ISSUE THREAD

**Issue by GermanBluefox** [danielzzz/node-ping#17]
My english windows returns following if destination not reachable:
'''
C:>ping 192.168.1.72

Pinging 192.168.1.72 with 32 bytes of data:
Reply from 192.168.1.69: Destination host unreachable.
Reply from 192.168.1.69: Destination host unreachable.
Reply from 192.168.1.69: Destination host unreachable.
Reply from 192.168.1.69: Destination host unreachable.

Ping statistics for 192.168.1.72:
Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
'''
And 
lines[t].indexOf ('(0%')>0 
returns true on the "Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),"

**Comment by mondwan** [comment]
Please fire another ticket if there are any new problems. close #17
