### ISSUE TITLE
What is the size of the packet?

### ISSUE THREAD

**Issue by acklavidian** [danielzzz/node-ping#21]
What is the size of the packet being transferred and can i change it?

**Comment by wildeyes** [comment]
@acklavidian It seems ping uses the underlying `ping` of the OS, on windows (probably Linux too) it's  32 bytes. Whether you can change it is up to the OS, and `node-ping` probably doesn't support it.

**Comment by nevercast** [comment]
It supports an addition options argument which is likely passed to the system call. 
You will have to make Platform specific options to change the packet size.

**Comment by mondwan** [comment]
Please fire another new ticket if this is still a problem. Thanks
