### ISSUE TITLE
alive is always false on Windows

### ISSUE THREAD

**Issue by adnan-kamili** [danielzzz/node-ping#26]
You have added a Windows specific check:

         if (p.match(/^win/)) {
                var lines = outstring.split('\n');
               // this is my solution on Chinese Windows8 64bit
                result  = false;
                for (var t = 0; t < lines.length; t++) {
                    if (lines[t].search(/TTL=[0-9]+/i) > 0) {
                       result	= true;
                       break;
                   }
               }
          
            }
            else {
               result = (code === 0) ? true : false;
           }

If this check for windows is removed all together, it works fine. code returns 1 on failure in my Windows 7 machine. Following code is enough for Windows too:

     ls.on('exit', function (code) {
            var result;
		   result = (code === 0) ? true : false;
           deferred.resolve({
               host: addr,
               alive: result,
               output: outstring
           });
        });

**Comment by mondwan** [comment]
According to the [patch][1] here, it seems exit code for window is incorrect for unreachable host.

As I do not have a window machine, can you verify this?

[1]: https://github.com/danielzzz/node-ping/commit/828f39bab9a114ddc1f83f2ad2fd9fc3f0f50437#diff-bf547ed104c846db825748b5b746d6f3R49

**Comment by jupe** [comment]
there is bug in line https://github.com/danielzzz/node-ping/blob/master/lib/ping-promise.js#L86, for loop  try to search array indexes and it should instead loop actual lines...

**Comment by mondwan** [comment]
oops. Thanks for pointing out.

**Comment by mondwan** [comment]
Please try and let us know whether there are any problems :D

**Comment by nick-woodward** [comment]
@mondwan Your changes are working for me on Windows 7.

**Comment by mondwan** [comment]
Close

**Comment by jlengrand** [comment]
Hi there, 

Sorry to comment on a closed issue, but it looked relevant.
I have just installed and tried node-ping and it looks like alive is always false on my Windows 10 machine. 

Nothing very special with my system I think (no specific charset being used). 

I am using the latest version from npm. Anything I may have missed?

**Comment by mondwan** [comment]
Have you tried the one in github? Hopefully, the npm one does not fix this
issue yet.

**Comment by jlengrand** [comment]
Hum, you are right @mondwan the version from Github indeed does not have the same issue. 

Is there any way when the npm version will be fixed?

**Comment by danielzzz** [comment]
@jlengrand soon, hopefuly. 
@mondwan If you're ok with this I will publish a new 2.1 version shortly

**Comment by jlengrand** [comment]
@danielzzz Looking forward, thanks for the good work!

**Comment by mondwan** [comment]
No problem. Please release that patch. Thanks

**Comment by danielzzz** [comment]
v2.1 published to NPM - thanks to everyone for your contributions!
