### ISSUE TITLE
Output race-condition

### ISSUE THREAD

**Issue by MiniGod** [danielzzz/node-ping#29]
There is a race condition in which sometimes the [`ls.stdout.on('data',...)` event][ondata] is fired after the [`ls.on('exit', ...` event][onexit], resulting in `outstring` being `''` (empty string).

[ondata]: https://github.com/danielzzz/node-ping/blob/master/lib/ping-promise.js#L95-L97
[onexit]: https://github.com/danielzzz/node-ping/blob/master/lib/ping-promise.js#L105

**Comment by mondwan** [comment]
Yes. This is indeed a bug.

In my MAC, I can reproduce easily for such racing condition if ping's response faser than 200 ms (Running `example/example2.js`).

After studying a while, according to [nodejs spec][1], `event exit` will be emitted even stdout does not finished yet.

Hopefully, we need to replace `event exit` with `event close` instead.

[1]: https://nodejs.org/api/child_process.html#child_process_event_close

**Comment by mondwan** [comment]
Close. Feel free to reopen or issue another new ticket if there are problems follow up.
