### ISSUE TITLE
Response with unknown request ID, Consider increasing timeouts ?

### ISSUE THREAD

**Issue by irom77** [danielzzz/node-ping#30]
I got messages 'Response with unknown request ID from 10.193.165.1. Consider increasing timeouts (21946 ms old?).' But when I ping 10.193.165.1 response is fine , please advise
```
$ ping 10.193.165.1
PING 10.193.165.1 (10.193.165.1) 56(84) bytes of data.
64 bytes from 10.193.165.1: icmp_seq=1 ttl=62 time=80.0 ms
^C
--- 10.193.165.1 ping statistics ---
2 packets transmitted, 1 received, 50% packet loss, time 1052ms
rtt min/avg/max/mdev = 80.084/80.084/80.084/0.000 ms
```

**Comment by danielzzz** [comment]
I believe it is something you're getting from your system. this library executes queries using the underlying system ping program, parses and returns the output.

**Comment by mondwan** [comment]
Please open another new ticket if this is still a problem. Thanks
