### ISSUE TITLE
In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE 

### ISSUE THREAD

**Issue by bgobi1991** [danielzzz/node-ping#31]
Hi Team,

I got following error when run npm install

npm WARN package.json net-ping@1.1.12 No README data
/
> raw-socket@1.4.0 install /var/www/html/netping/node_modules/raw-socket
> node-gyp rebuild

make: Entering directory '/var/www/html/netping/node_modules/raw-socket/build'
  CXX(target) Release/obj.target/raw/src/raw.o
../src/raw.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE raw::SocketWrap::Send(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/raw.cc:662:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (args[3]);
   ^
../src/raw.cc:663:44: error: ‘address’ was not declared in this scope
   struct sockaddr_in6 addr = uv_ip6_addr (*address, 0);
                                            ^
../src/raw.cc:673:3: error: ‘Utf8String’ is not a member of ‘v8::String’
   String::Utf8String address (info[3]);
   ^
../src/raw.cc:674:43: error: ‘address’ was not declared in this scope
   struct sockaddr_in addr = uv_ip4_addr (*address, 0);

**Comment by dougluce** [comment]
@bgobi1991 are you sure this is from node-ping?  It looks like that error came from installing net-ping.

**Comment by mondwan** [comment]
Please open another new ticket if this is still a problem. Thanks
