### ISSUE TITLE
Allow ping to specify IPv4, IPv6 or 'any protocol'

### ISSUE THREAD

**Issue by ajmas** [danielzzz/node-ping#33]
Allow for ping options to specify the type of ping to be done. For example, somethings like:

```
opts = {
    ipv4: true,
    ipv6: true
};

ping.sys.probe(host, function(isAlive) {

}, opts);
```

If something like this can already be done, please could you indicate the correct way in the documentation.

**Comment by dodekeract** [comment]
A workaround could be to use the IPv4 or IPv6 address directly instead of the domain.

**Comment by BlessJah** [comment]
Not necessarily. Some systems may have separate `ping` and `ping6` commands (it requires further investigation).

**Comment by elad** [comment]
I'd like to have this functionality too. Submitted PR #67.

@ajmas it needs a single toggle (e.g. `v6`) otherwise you could potentially specify both and I think that's odd behavior.

**Comment by mondwan** [comment]
Close this issue and please give us a hand on #79 so that we can better support the ipv6.

Thanks :)
