### ISSUE TITLE
No response with node 4.x

### ISSUE THREAD

**Issue by DominicBoettger** [danielzzz/node-ping#34]
The promise version doesn't seem to work. I tried it under MacOSX. The promise function is not executed.

````
'use strict';
var ping = require('ping');
console.log('here');
var host = 'heise.de';
ping.promise.probe(host).then(function (res) {
    console.log(res);
    console.log('done');
});

**Comment by mondwan** [comment]
How about catching error?

```javascript
ping.promise.probe(host).then(function (res) {
    console.log(res);
    console.log('done');
}).catch(function (err) {console.log(err);});
```

**Comment by DominicBoettger** [comment]
No result.
The script is just hanging and not exiting.

**Comment by mondwan** [comment]
Ah I know the problem.

```javascript
var ping = require("../index");

var hosts = ['heise.de'];

hosts.forEach(function (host) {
    console.log('host', host);
    ping.promise.probe(host, {
            extra: ['-n', '-t 2', '-c 1', host],
        })
        .then(function (res) {
            console.log(res);
        })
        .catch(function (err) {
            console.error('err', err);
        })
        .done();
});
```

The promise implementation does not take care the argument you need. Before the patch, you can pass arguments as above.

## output
```
host heise.de
{ host: 'heise.de', alive: false }
```

**Comment by dbpeng** [comment]
But alive is always false on MacOSX... to any host :-o

**Comment by dbpeng** [comment]
I see, for my case, it seems extra: ['-n', '-t 2', '-c 1', host] -> extra: ['-n', '-t 2', '-c 1'] and can be ok.

If we didn't specify '-c <times>' then by default OSX will ping forever so the ping program will never ends.
