### ISSUE TITLE
Fails on linux w/node 4.3

### ISSUE THREAD

**Issue by AllenKll** [danielzzz/node-ping#41]
There seems to be an issue using arguments with spaces with the child_process.spawn method on linux.  This manifests itself in an error when using this module. (following that all hosts are dead)

example: from builder/linux.js
```
if (config.timeout) {
        ret.push(util.format('-w %d', config.timeout));
    }
```
The space between the '-w' and the integer causes spawn to think that these are two different arguments one with '-w' and one with (for example) ' 2', this causes ping to believe that the integer part of the argument is SPACE TWO which is an invalid number.  
This error is received: `stderr: ping: invalid number ' 2'`

Removing this space in the configuration arguments for Linux seems to correct the issue.

**Comment by mondwan** [comment]
As the suggestion from [stackoverflow][1], split the arguments as 2 separate string literals.

The patch should fix your problem. I have tested on node v5.11.1 and v4.4.4 (I cannot get v4.3 yet).

Let me know if there are anymore problem.

[1]: http://stackoverflow.com/questions/10941545/nodejs-child-process-spawn-does-not-work-when-one-of-the-args-has-a-space-in-it

**Comment by mondwan** [comment]
Close this ticket
