### ISSUE TITLE
output parsing

### ISSUE THREAD

**Issue by fithwith** [danielzzz/node-ping#44]
I noticed that the output is given as raw text, it will be really helpful to parse it and return a JSON object with ttl, time...

**Comment by mondwan** [comment]
Hi, have you tried the promise one? Information you need should be included I guess?

**Comment by fithwith** [comment]
yeah its the promise one, this is the code that I'm using

`ping.promise.probe("test").then(function (res) {
       console.log(res);
      });`

the object returned contain:  host,alive and output

**Comment by mondwan** [comment]
Try to use the latest one in github. There is a time attribute may suit your needs.

By the way, it should be no difference between platforms

**Comment by fithwith** [comment]
I replaced the code from npm by the github one and now I have the time field, but its giving the time in the first try, not the average.
it will be better if the JSON object contain the ttl, packet received/lost, the time of each packet, max/min/avg.

**Comment by mondwan** [comment]
This maybe hard as results of ping varied on languages and platforms. If there are sufficient examples for ping in different languages and platforms, I can try to work on that.

**Comment by mondwan** [comment]
Together with the PR #47, result from this module getting richer. It should solve your problem.

**Comment by mondwan** [comment]
Close. Please comment if patches in master do not work.
