### ISSUE TITLE
update the npm module

### ISSUE THREAD

**Issue by sembaye** [danielzzz/node-ping#46]
Hi,
i'm using the library on an embedded Linux OS where an stderror occured. 
When i installed the module via _npm install ping_ i found out that the src-code is different compared with the git src-code.
npm installed the version 0.1.10. You can not  install the 0.2.0 Version with _npm install ping @0.2.0_.

**Comment by danielzzz** [comment]
sorry, I've been pretty busy recently to publish the recent changes to npm... please use the github version for now... thanks

**Comment by mondwan** [comment]
At this moment, source codes in github does not synchronized with npm.

I strongly recommend you to use source in github instead as they are more
update and fixed certain bugs.

2016年8月18日 17:47於 "sembaye" <notifications@github.com>寫道：

**Comment by danielzzz** [comment]
published 0.2
