### ISSUE TITLE
Update on npm

### ISSUE THREAD

**Issue by andrea-latini** [danielzzz/node-ping#50]
Hi,
I have a bug about pinging in Windows; I saw the source code in github but it is already fixed (line 86 in "ping-promise.js"). Could you please publish a new release version in NPM so I could use the newest module with the bug fixed? Thanks

**Comment by mondwan** [comment]
In the mean time, you can try to use the latest one from github. Thanks.

**Comment by danielzzz** [comment]
v2.1 published to NPM
