### ISSUE TITLE
Wrong alive result on different systems

### ISSUE THREAD

**Issue by aramix** [danielzzz/node-ping#51]
I am running ping with promise on macOS and it works fine, however when I pushed the code to production server which is
`Linux 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
I get this result

```
{ 
  host: 'google.com',
  alive: false,
  output: 'PING google.com (46.162.192.44) 56(84) bytes of data.\n64 bytes from 46.162.192.44: icmp_seq=1 ttl=60 time=1.62 ms\n64 bytes from 46.162.192.44: icmp_seq=2 ttl=60 time=1.53 ms\n\n--- google.com ping statistics ---\n2 packets transmitted, 2 received, 0% packet loss, time 1001ms\nrtt min/avg/max/mdev = 1.531/1.577/1.623/0.046 ms\n',
  time: 1.62 
}
```

Why is the alive value false when the packet loss is 0%. I ended up manually checking the out put for the correct result.

**Comment by mondwan** [comment]
The status of alive solely depends on the exit code from the system ping
command at this moment.

If it is zero, alive is true else false.

Can you state your Ubuntu version and test your exit code for a successful
run from system ping?

**Comment by aramix** [comment]
@mondwan thanks for getting back.
Ubuntu version details:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Sample output:
PING google.com (216.58.217.78) 56(84) bytes of data.
64 bytes from iad23s41-in-f78.1e100.net (216.58.217.78): icmp_seq=1 ttl=55 time=7.20 ms
64 bytes from iad23s41-in-f78.1e100.net (216.58.217.78): icmp_seq=2 ttl=55 time=7.23 ms
64 bytes from iad23s41-in-f78.1e100.net (216.58.217.78): icmp_seq=3 ttl=55 time=7.26 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 7.202/7.233/7.262/0.073 ms

**Comment by mondwan** [comment]
Interesting. Can you try following?

ping -c4 localhost ; echo$?

Output from the echo should be zero?

**Comment by aramix** [comment]
ping -c4 localhost ; echo $?
the output of this is 0

**Comment by mondwan** [comment]
Change the implementation to parse output directly. It should fix your problem. Can you try one more time with the latest version from github ?

**Comment by aramix** [comment]
you mean without promises?

**Comment by mondwan** [comment]
Both of them should work fine from now on (I guess) :P

**Comment by mondwan** [comment]
Close. Please comment if patches in the master do not work. Thanks

**Comment by aramix** [comment]
@mondwan sorry for late reply, was a little busy with other stuff.
I have updated the node-ping to the current 0.2.1 release and still the problem persists.

**Comment by mondwan** [comment]
How about the version in github? I guess we haven't published the latest
one to npm yet.

**Comment by aramix** [comment]
I'll try that tonight. Thanks)

**Comment by aramix** [comment]
I'm getting this error with the version from master:

```
/home/proxy-manager/node_modules/ping/lib/ping-promise.js:76
        __.each(lines, parser.eat, parser);
                             ^

TypeError: Cannot read property 'eat' of null
    at ChildProcess.<anonymous> (/home/proxy-manager/node_modules/ping/lib/ping-promise.js:76:30)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by mondwan** [comment]
:D Sorry, I forgot to push the linux's implementation and I skipped the linux test cases. Therefore, I have not noticed that until now.

I have added the linux implementation. Please try again. Thanks

**Comment by aramix** [comment]
ah, I see )))
seems to be working now, thanks 👍 
when will this be pushed to npm?

**Comment by mondwan** [comment]
Published. Please checked
