### ISSUE TITLE
How can I stop execution if I get an alive IP?

### ISSUE THREAD

**Issue by jmj4you** [danielzzz/node-ping#52]
I want to stop next ping when I get an alive IP.

**Comment by aramix** [comment]
use Promises and return whenever alive is true

**Comment by mondwan** [comment]
Hello,

You can check options provided by your system ping.

For example, in mac os, provide `-o` in the `extra` which will cause ping exit immediately after 1 successful response back.

**Comment by jmj4you** [comment]
Thank you very much
