### ISSUE TITLE
mistake 'avg' with 'max' in promise result 

### ISSUE THREAD

**Issue by oxcafebabe** [danielzzz/node-ping#54]
in osx and linux the footer is sth like `round-trip min/avg/max/stddev = 4.504/5.157/6.147/0.508 ms`, but it seems parse the 2nd number as `result.max` and 3rd number as `result.avg`

see https://github.com/danielzzz/node-ping/blob/master/lib/parser/mac.js#L68

**Comment by mondwan** [comment]
oops. Thanks for pointing out
