### ISSUE TITLE
0.2.2 pushed to npm?

### ISSUE THREAD

**Issue by jritsema** [danielzzz/node-ping#55]
When will 0.2.2 be pushed to [npm](https://www.npmjs.com/package/ping)?  Right now it has 0.2.1  Just curious.

**Comment by mondwan** [comment]
Hello @danielzzz , I guess we are good to release 0.2.2 :D

**Comment by danielzzz** [comment]
@mondwan and collaborators thank you very much for all your input and hard work. 
I have pushe 0.2.2 to npm
