### ISSUE TITLE
Timeout dimension

### ISSUE THREAD

**Issue by eapyl** [danielzzz/node-ping#56]
Hi there, thank you for great package.

It will be great to add in README that 'timeout' parameter is in 'seconds', not 'milliseconds'. Just small suggestion, feel free to close this issue. Thanks!

**Comment by mondwan** [comment]
Which platform you are?

2017年1月20日 03:23，"eapyl" <notifications@github.com>寫道：

**Comment by eapyl** [comment]
Platform? I am using it in electron on Ubuntu. But it is not clear that 'timeout' parameter should contain value in seconds, not milliseconds.

**Comment by mondwan** [comment]
Really? Units for ping in Ubuntu should be ms. Can you copy your system's
ping output or take a screenshot for us to take a look?

2017年1月21日 00:42，"eapyl" <notifications@github.com>寫道：

**Comment by eapyl** [comment]
Ah, you are right. I looked into win.js instead of linux.js file ib 'builder' folder.
I am using version ping.version = 0.2.1
win.js:
![image](https://cloud.githubusercontent.com/assets/1629511/22172793/ce5670d8-dfb0-11e6-8ea8-b40b5a34bae2.png)
linux.js:
![image](https://cloud.githubusercontent.com/assets/1629511/22172805/26df4b3a-dfb1-11e6-933c-c29377f19e61.png)

This differences confused me. Sorry for bothering.

**Comment by mondwan** [comment]
Ah.. I have misunderstood too.

Arguments `timeout` in our configuration is in seconds while the one in window is in milliseconds. So, we need to convert them accordingly. I have added a comment in `win.js` to show the reason.

Close this ticket. Feel free to reopen it or create a new one if there are any more problems.
