### ISSUE TITLE
chinese windows can`t run the example

### ISSUE THREAD

**Issue by cnfi** [danielzzz/node-ping#59]
Hi~

OS: windows 7
language: chinese

![image](https://cloud.githubusercontent.com/assets/1331723/23102616/4fa5ab02-f6e7-11e6-92b1-cc24c9cc8937.png)

I think this question should be the encoding format~

My project can run on Mac, but it can not run on Windows
![image](https://cloud.githubusercontent.com/assets/1331723/23102656/2d6debfc-f6e8-11e6-9ce7-e65f0f7c75ea.png)

**Comment by cnfi** [comment]
I think that by using the  third-party library iconv-lite, you can solve the problem

https://github.com/ashtuchkin/iconv-lite

**Comment by mondwan** [comment]
Nope. I don't think so.
Actually, `example2.js` cannot be run on window due to the argument `-i 2`.

My guess for the missing characters is something about invalid argument `-i 2`

**Comment by mondwan** [comment]
For example,

```
C:\Users\Mond>ping -i2 google.com
選項 -i2 的值不正確，正確的範圍是從 1 到 255。
```

**Comment by cnfi** [comment]
Thank you for your reply! 
In that example, I did not pass any parameters

example2.js:
```
var ping = require("../index");

var hosts = ['www.taobao.com', 'google.com', 'yahoo.com'];

// Running with default config
hosts.forEach(function (host) {
    ping.promise.probe(host)
        .then(function (res) {
            console.log(res);
        })
        .done();
});
```

![image](https://cloud.githubusercontent.com/assets/1331723/23123756/af88df9a-f7a4-11e6-8241-895aaa3b3f48.png)

**Comment by cnfi** [comment]
I tried to modify the ping-promise.js file and found that the CMD could show the returned Chinese information, but the program still failed

![image](https://cloud.githubusercontent.com/assets/1331723/23124364/8c07021a-f7a7-11e6-9f1e-bfc6dff5a6d4.png)

**Comment by mondwan** [comment]
Hello, thanks for the hard work.

In my opinion, error you post is odd. Have you modified our source code? It
should be `String` instead of `string`.


2017年2月20日 20:03，"owen" <notifications@github.com>寫道：

**Comment by cnfi** [comment]
你好~ 可以中文吗？

string是我写错了，做截图时候，为了有新旧代码方便对比，手写打上去的。

源码就修改了GBK编码相关的逻辑，如果恢复，直接报错：
![image](https://cloud.githubusercontent.com/assets/1331723/23125633/c2e5117c-f7ad-11e6-8eb2-bb24074366fa.png)

另外，换行在我这个操作系统下是\r\n，而不是\n，这个也是个问题哈~
![image](https://cloud.githubusercontent.com/assets/1331723/23125657/e166ce60-f7ad-11e6-89c7-2f5336d27889.png)

我google了下，很多都是说控制台只识别GBK的，而node默认输出是utf-8

**Comment by mondwan** [comment]
能否提供 一個跑ping 的範本看看, 在WINDOW 指令列中隨便ping 一個HOST
例子:
https://github.com/danielzzz/node-ping/blob/master/test/fixture/window/zh/sample1.txt

```
Ping google.com [216.58.203.14] (使用 32 位元組的資料):
回覆自 216.58.203.14: 位元組=32 時間=2ms TTL=54
回覆自 216.58.203.14: 位元組=32 時間=2ms TTL=54
回覆自 216.58.203.14: 位元組=32 時間=3ms TTL=54
回覆自 216.58.203.14: 位元組=32 時間=3ms TTL=54

216.58.203.14 的 Ping 統計資料:
    封包: 已傳送 = 4，已收到 = 4, 已遺失 = 0 (0% 遺失)，
    大約的來回時間 (毫秒):
        最小值 = 2ms，最大值 = 3ms，平均 = 2ms
```

**Comment by mondwan** [comment]
應該解決了 抄最新的源碼 試試看

**Comment by cnfi** [comment]
重新clone了一份代码，执行example2.js ，换行问题解决了，但返回还是乱码。。。悲剧。。。
```
cnfi@cnfi-GAME-PC MINGW64 ~/Desktop/test/node-ping/examples (master)
$ node example2.js
```

![image](https://cloud.githubusercontent.com/assets/1331723/23169005/1d9dc208-f885-11e6-9ce8-55a1f7d3d748.png)

**Comment by mondwan** [comment]
嗯 因為我沒有解決編碼問題, 只令到 數字都能被讀取

編碼問題在這一行

https://github.com/danielzzz/node-ping/blob/master/lib/ping-promise.js#L67

我沒有方法知道 WINDOW在用什麼編碼 還有 不同的window 對編碼有沒有分別

**Comment by cnfi** [comment]
```
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\cnfi\Desktop\test\node-ping\examples>ping www.taobao.com

正在 Ping www.taobao.com.danuoyi.tbcache.com [122.228.74.168] 具有 32 字节的数据
:
来自 122.228.74.168 的回复: 字节=32 时间=16ms TTL=46
来自 122.228.74.168 的回复: 字节=32 时间=23ms TTL=46
来自 122.228.74.168 的回复: 字节=32 时间=16ms TTL=46
来自 122.228.74.168 的回复: 字节=32 时间=21ms TTL=46

122.228.74.168 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 16ms，最长 = 23ms，平均 = 19ms
```

**Comment by mondwan** [comment]
除了編碼 其他數據有錯?

**Comment by cnfi** [comment]
感谢哈，别的错误没有了！
这个问题我想还是close吧，应该是操作系统的诡异问题~:joy:

**Comment by mondwan** [comment]
you are welcome. Happy coding :P
