### ISSUE TITLE
How to get a single output (average ping) instead of entire formatted output?

### ISSUE THREAD

**Issue by IceQubed** [danielzzz/node-ping#60]
I'm trying to use this code to simply output the average ping. The output of `console.log(res);` gives an example output of:

```
{ host: '192.168.1.102',
  alive: true,
  output: '\r\nPinging 192.168.1.102 with 32 bytes of data:\r\nReply from 192.168.1.102: bytes=32 time<1ms TTL=64\r\n\r\nPing statistics for 192.168.1.102:\r\n    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),\r\nApproximate round trip times in milli-seconds:\r\n    Minimum = 0ms, Maximum = 0ms, Average = 0ms\r\n',
  time: undefined }
```

I just want to get the number of average ping time, and have tried `console.log(res.avg);` however this just returns `undefined` - weirdly enough, doing `console.log(res.alive);` returns true, so this method of using `res.foo` should work. I'm on Windows but need to be able to run this on Linux too.

Am I stuck with parsing the full `console.log(res);` output?

**Comment by mondwan** [comment]
Hopefully, you are using the npm one. Please consider using the latest
version in Github.

2017年2月20日 上午3:52，"Ben Adamson" <notifications@github.com>寫道：

**Comment by mondwan** [comment]
Close it now. Feel free to reopen it if there are any more problems.
