### ISSUE TITLE
How can I return the value of the function. 

### ISSUE THREAD

**Issue by sachethegde** [danielzzz/node-ping#61]
Hello, I am looking for help in solving this problem.  I want to return the result of this function which will be used by some other function. 

`pingTest(){
    let msg='initialized';
    ping.promise.probe('www.google.com',{
    extra:['-o']}).then(function(res){
    msg=res;

  });
      console.log(msg);
      return msg;
  }`

My pingTest function return 'initialized'. How can I get the 'res' value into 'msg' and return that from 'pingTest' function? 

I have gone through Async function concepts in js, still unable to resolve this. 

Thanks,

**Comment by mondwan** [comment]
Firstly, reformat this in ES5 coz I am not familiar with ES6 syntax

```javascript
function pingTest() {
   var msg='initialized';
   ping.promise.probe('www.google.com',{extra:['-o']}).then(function(res){
        msg=res;
   });
   console.log(msg);
   return msg;
}
```

This is not the correct way for using promise. It should be used like that.

```javascript
function pingTest() {
   return ping.promise.probe('www.google.com',{extra:['-o']}).then(function(res){
        console.log('Inside Response :', res);
        return res;
   })
}

// How to run pingTest
pingTest().then(function (res) {
   console.log('External Response :', res);
});
```

By the way, async chapter from [YDKJS][1] has a really great explaination for various async solution in JS. You can take a look.

[1]: https://github.com/getify/You-Dont-Know-JS

**Comment by mondwan** [comment]
So, I guess problem solved. Feel free to reopen it if there are any more problems
