### ISSUE TITLE
Language support ?

### ISSUE THREAD

**Issue by RedRelay** [danielzzz/node-ping#64]
Hi,

I get an error when I ping a alive computer. I'm using a French version of W10

Here is my code used using Windows 10 :
```
var ping = require ("ping");
ping.sys.probe('8.8.8.8', function(isAlive){
	console.log(isAlive)
});
```

```
.\ping\lib\parser\win.js:56
        this._times.push(parseFloat(match[1], 10));
                                         ^

TypeError: Cannot read property '1' of null
    at WinParser._processBody (.\ping\lib\parser\win.js:56:42)
    at WinParser.parser.eat (.\ping\lib\parser\base.js:125:14)
    at .\underscore\underscore.js:73:21
    at Function._.each._.forEach (.\underscore\underscore.js:153:9)
    at ChildProcess.<anonymous> (.\ping\lib\ping-promise.js:76:12)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
```

After investigation, I found that french version are not supported (I think).
I replace this : 
```
if (kvps.length >= 3) {
        // XXX: Assume time will alaways get keyword ms for all language
        var timeKVP = __.find(kvps, function (kvp) {
            return kvp.indexOf('ms') >= 0;
        });
        var regExp = /([0-9\.]+)/;
        var match = regExp.exec(timeKVP);

        this._times.push(parseFloat(match[1], 10));
    }
```
by :

```
if (kvps.length >= 3) {
        // XXX: Assume time will alaways get keyword ms for all language
        var timeKVP = __.find(kvps, function (kvp) {
            return kvp.indexOf('temps') >= 0;
        });
        var regExp = /([0-9\.]+)/;
        var match = regExp.exec(timeKVP);

        this._times.push(parseFloat(match[1], 10));
    }
```

And it works fine. Maybe multi-language is not supported yet. I put it here anyway in case some ppl want to implement a solution.

**Comment by mondwan** [comment]
As our codes relies on parsing system output, code may break if format of
the output varied.

Could you provide an example of ping from w10 terminal?

2017年5月1日 下午7:02，"Alexandre DUPONCHEL" <notifications@github.com>寫道：

**Comment by RedRelay** [comment]
I've edited my issue with more detail and a fix.
Here is an example of my terminal output using a french w10 terminal :
`Réponse de 8.8.8.8 : octets=32 temps=29 ms TTL=57`

**Comment by mondwan** [comment]
For short term solution, you may try to switch your OS into English
language. It should work.

For long term, hopefully, we need to update our code in order to support
German language?

2017年5月1日 下午7:25，"Alexandre DUPONCHEL" <notifications@github.com>寫道：

I've edited my issue with more detail and a fix.
Here is an example of my terminal output using a french w10 terminal :
Réponse de 8.8.8.8 : octets=32 temps=29 ms TTL=57

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/danielzzz/node-ping/issues/64#issuecomment-298320859>,
or mute the thread

**Comment by mondwan** [comment]
@RedRelay can you post or upload an example of ping response just like below example?

```
Pinging www.some-domain.com [127.0.0.1] with 32 bytes of
Reply from 127.0.0.1: bytes=32 time=564ms TTL=237
Reply from 127.0.0.1: bytes=32 time=555ms TTL=237
Reply from 127.0.0.1: bytes=32 time=554ms TTL=237
Reply from 127.0.0.1: bytes=32 time=548ms TTL=237

Ping statistics for 127.0.0.1:
   Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)
   Approximate round trip times in milli-seconds:
      Minimum = 548ms, Maximum = 564ms, Average = 555ms
```

**Comment by mondwan** [comment]
Continue this issue at #65
