### ISSUE TITLE
Split issue with windows ping format in French

### ISSUE THREAD

**Issue by jsdidierlaurent** [danielzzz/node-ping#65]
I don't know why, but in french they add space between the time and 'ms'
This space create issue in _processBody function in lib/parser/win.js.

![capture](https://cloud.githubusercontent.com/assets/11354381/26024010/050ec16e-37c9-11e7-819c-a9b4d7de8d31.JPG)

**Comment by mondwan** [comment]
Ahh, issue sames with #64 . Can you upload a text version for the complete ping run from terminal? As I cannot patch this without a concrete example from french system :)

**Comment by jsdidierlaurent** [comment]
Yes sure !

`> ping 127.0.0.1

Envoi d’une requête 'Ping'  127.0.0.1 avec 32 octets de données :
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128
Réponse de 127.0.0.1 : octets=32 temps<1ms TTL=128

Statistiques Ping pour 127.0.0.1:
    Paquets : envoyés = 4, reçus = 4, perdus = 0 (perte 0%),
Durée approximative des boucles en millisecondes :
    Minimum = 0ms, Maximum = 0ms, Moyenne = 0ms`

`> ping 8.8.8.8

Envoi d’une requête 'Ping'  8.8.8.8 avec 32 octets de données :
Réponse de 8.8.8.8 : octets=32 temps=6 ms TTL=58
Réponse de 8.8.8.8 : octets=32 temps=6 ms TTL=58
Réponse de 8.8.8.8 : octets=32 temps=6 ms TTL=58
Réponse de 8.8.8.8 : octets=32 temps=6 ms TTL=58

Statistiques Ping pour 8.8.8.8:
    Paquets : envoyés = 4, reçus = 4, perdus = 0 (perte 0%),
Durée approximative des boucles en millisecondes :
    Minimum = 6ms, Maximum = 6ms, Moyenne = 6ms`

**Comment by BlueBird67** [comment]
For french system @Windows 10, the simple correction (but will work only for french after that), is to modify the line 51 in lib/parser/win.js

`return kvp.indexOf('ms') >= 0;`

with

`return kvp.indexOf('temps') >= 0;`

**Comment by mondwan** [comment]
I am trying to work a way that good for existing system. Hopefully, the
last choice is adding a if statement for special handling French system

2017年5月18日 18:33，"BlueBird67" <notifications@github.com>寫道：

**Comment by mondwan** [comment]
@jsdidierlaurent , can you give one more example which involves a domain name?

say, ping google.com?

**Comment by mondwan** [comment]
Please try again with the latest version in github. Thanks.

**Comment by jsdidierlaurent** [comment]
Great, it works !
Thanks !

**Comment by adamtal3** [comment]
Can this be published into npm?

**Comment by agpmilli** [comment]
It seems like the version on npm still has this issue when windows language is French.
Can the fix be pushed on npm?
Thanks.

**Comment by Sazarov** [comment]
Hey, is this fix going to be published to NPM? We're facing a similar issue with Spanish windows

**Comment by mondwan** [comment]
May I know is it fixed if you are using the latest version in github
instead of npm?

在 2019年6月21日週五 21:59，Sazarov <notifications@github.com> 寫道：

**Comment by mnakalay** [comment]
I am on a French Windows 7 system

I can confirm that this:

- Doesn't work from NPM
- Works just fine with the latest Github version
