### ISSUE TITLE
support ping host with port?

### ISSUE THREAD

**Issue by devil5263** [danielzzz/node-ping#66]
I didn't find the function of ping with port in document, I want to know this can work?

**Comment by mondwan** [comment]
Nope. It does not support ping with port as ping is layer 3 stuff while
port is layer 4 stuff.

If you need them, nodejs builtin socket module will help.

2017年6月8日 14:26，"devil" <notifications@github.com>寫道：

**Comment by devil5263** [comment]
@mondwan Thanks so much , I will try that module
