### ISSUE TITLE
Using another interface as source

### ISSUE THREAD

**Issue by Kerwood** [danielzzz/node-ping#75]
Hi.. Thanks for at super nice and simple module.
Minor thing really.. On the documentation on npmjs.com there a minor typo..
Under `Tradition calls with configuration`. The `extra:` line is like below.
```
...
extra: ["-i 2"],
...
```
But should really be like this.
```
...
extra: ['-i', '2'],
...
```
Just like the documentation here on Github. Or else it wont work.
Thanks

**Comment by danielzzz** [comment]
thank you! would you mind sending a PR?

**Comment by Kerwood** [comment]
Its the documentation on npmjs.com... I cant really do much there, can I ?

**Comment by mondwan** [comment]
You can send a PR with changed documents (and corrected example?) To us.
Then, we can merge and updated the one in npm.

Thanks

2018年1月26日 20:00 於 "Kerwood" <notifications@github.com> 寫道：

**Comment by Kerwood** [comment]
I'm not sure what you mean.. The documentation on Github is correct. Nothing to fix there.
Its on npmjs.com theres an issue. Update the documentation on npmjs.com with Github and you are golden.

**Comment by danielzzz** [comment]
ok, thank you - I guess it's a matter of publishing it there. I will take care of it soon. kind regards, dan

**Comment by mondwan** [comment]
Let us know if you have more questions
