### ISSUE TITLE
Publishing on npmjs.com

### ISSUE THREAD

**Issue by woicha** [danielzzz/node-ping#76]
Hi guys,
many thanks for your very good and easy to use module, especially since you solved the parsing issues to support many international versions of Windows. I'm using a german Windows 10 Enter Enterprise edition and everything seems to work perfect with the actual version on **github**.
My only problem is, that on **npmjs.com** an older version seems to published. Could you publish the newest version there so that I'm able to use the "_npm install ..._" command in our project? Or is there another way to install the actual version under our project's "_node_modules_" subdirectory? (Sorry, I'm a beginner.)
By the way: the entry "version" in the newest package.json is "0.2.2"; the same shows in the package.json I received by running the "_npm install ..._" command.

Thanks.

**Comment by mondwan** [comment]
Try using this format in `package.json` which copied from this [stackoverflow post][1]

```
"package": "git+https://github.com/username/package.git#commit"
```
[1]: https://stackoverflow.com/questions/14187956/npm-install-from-git-in-a-specific-version

So, in your case, it will be look like that if you want to use the `master` version in github

```
"node-ping": "https://github.com/danielzzz/node-ping.git#master"
```

**Comment by woicha** [comment]
Thank you for your prompt help. I replaced the line `"ping": "^0.2.2",` created by 'npm install ping'
by 
`"ping": "git+https://github.com/danielzzz/node-ping#master",`. 

To work with a specific commit (for instance the current master commit) use: 
`git+https://github.com/danielzzz/node-ping/commit/1601458126cc1dd0c31db8150f2e6b2a40570a7f`
