### ISSUE TITLE
Is not working on mobile

### ISSUE THREAD

**Issue by 4sh3** [danielzzz/node-ping#81]
Hi,

I have created a npm package with your ping package but seems that is not working on android mobile phone, I am using an S8 with termux. 

`
npm install is-server-alive 
`

**Comment by mondwan** [comment]
Hello, we haven't though about mobile platform. Can you elaborate your question? For example, what kind errors you get and what kind of expectation you have under your situation?

In my opinion, you need to ensure `ping` is available on your platform first.

**Comment by mondwan** [comment]
Let us know if you have any more questions. Close
