### ISSUE TITLE
Is broadcast ping supported?

### ISSUE THREAD

**Issue by komalpharate** [danielzzz/node-ping#83]

**Comment by mondwan** [comment]
Not quite. Depends on your system, you can send your platform specific
flags for using broadcast ping via an extra key

在 2018年5月8日週二 20:23，Komal Pharate <notifications@github.com> 寫道：

**Comment by komalpharate** [comment]
`var ping = require('ping');

var hosts = ['10.9.44.255'];
hosts.forEach(function(host){
    ping.promise.probe(host, {
        timeout: 10,
        extra: ['-b'],
    }).then(function (res) {
        console.log("Result-",res.alive);
    });
});`
This should work?

**Comment by mondwan** [comment]
It should work for Linux system as -b should be a flag on linux's ping for
supporting boardcast flag

在 2018年5月11日週五 15:05，Komal Pharate <notifications@github.com> 寫道：
