### ISSUE TITLE
Can you add lost percentage?

### ISSUE THREAD

**Issue by ccgview** [danielzzz/node-ping#85]
Can you add the loss percentage as and perimeter output?
Thanks

**Comment by mondwan** [comment]
It sounds a good idea. Can you upload a fixture which include some loss figures for us to test our implementation?

**Comment by adamhancock** [comment]
I used regex to get the lost percentage from the output property. 
result.output.match(/(\d+%)/gm)[0].replace("%", "")

**Comment by mondwan** [comment]
Patch has been merged. Please check it out.
