### ISSUE TITLE
Browser Not Supported Issue

### ISSUE THREAD

**Issue by KeeanoMartine2Gen** [danielzzz/node-ping#88]
I am running a React.js application and its setup per the documentation but I get this below issue:

Uncaught Error: Platform |browser| is not support
    at Function.factory.createBuilder (bundle.js:159786)
    at Object.probe (bundle.js:155314)
    at bundle.js:137844
    at d (raven.js:418)

Would love to use this library but just can't get it to work.

**Comment by mondwan** [comment]
This is relies on system `ping`. Such failure is expected if you are running on browser. As discussion in #73, if you would like to `ping` a website, you need to download favicon instead.
