### ISSUE TITLE
Doesn't work with busybox

### ISSUE THREAD

**Issue by NathanielHill** [danielzzz/node-ping#89]
Just for the record, this doesn't seem to work with the output from busybox's `ping`, which is quite common in Docker setups these days with so many `alpine` images.

For anyone coming across this trying to get this working on your alpine Docker image, try:

`RUN apk add iputils`

**Comment by mondwan** [comment]
Update the README to include your solution. THanks

**Comment by gwh-cpnet** [comment]
It is interesting though. `ping` command is workable in alpine shell.
