### ISSUE TITLE
Async ping to hosts

### ISSUE THREAD

**Issue by erolfedakar** [danielzzz/node-ping#93]
Hello,

I am trying to make async ping to hosts, in current we are sending ping all at the same time,

so I want to do first try ping to first hosts when getting a reply from first hosts to try second hosts, 

in current sending ping to all hosts same time.

**Comment by mondwan** [comment]
It should work for using with promise `ping`. In your case, you need something like a waterfall or series implementation. Here is the idea from bluebird

http://bluebirdjs.com/docs/coming-from-other-libraries.html#async.waterfall

Bluebird is simply a library for working with promise object. You can choose whatever promise library you like.
