### ISSUE TITLE
Not able to use this library with reactjs components. 

### ISSUE THREAD

**Issue by Venmathi2510** [danielzzz/node-ping#96]
Hi ,
I tried to use this with just a simple node js code and it worked. 

But i need to check for the ping status from UI end. (i.e Client) . I tried using this npm ping library. But im facing following issues: 

1. Ping is not recognized, if I import in the react component. 
![image](https://user-images.githubusercontent.com/40182461/57163432-d403b900-6db6-11e9-8532-bb0ffbad9c99.png)

2. Getting the following error while invoking it.

`ERROR in ./~/ping/lib/ping-promise.js
Module not found: Error: Cannot resolve module 'child_process' in C:\Users\Desktop\workspace\ui-react\node_modules\ping\lib
 @ ./~/ping/lib/ping-promise.js 15:9-33`

Please help me out, How I can use this for react js components as well.. I mean how  to implement the ping logic from client side.

**Comment by mondwan** [comment]
As ping is a system command, it is unable to use on web directly. If you want to `ping` a web page, please refer to the discussion in #73
